name: Create-File-Action

on: push

jobs:
  create-file:
    name: Create File on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create File
        run: |
          echo "HI this file is created and written by GitHub Actions CI/CD on self-hosted runner" > /home/ubuntu/githubaction
