name: Build-Docker-Images

on: push

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Nginx Docker Image
        run: docker build -t my-nginx-image ./nginx
