name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Change this to your defaulytt 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: docker build -t mynginx:latest /home/ubuntu/nginx

    - name: Run Docker container
      run: docker run -d -p 80:80 mynginx:latest

    # Add additional steps as needed, such as running tests or deploying.

